# Developer's Note: This is a sample _config.yml file offered with
# jekyll-theme-prologue for your convenience. To use it, move it to your
# project's root directory. Please note that the following lines are
# NECESSARY for Prologue to work correctly:
#
# theme: jekyll-theme-prologue
# collections: [sections]
#
# They activate the theme and tell Jekyll to find your homepage content
# in /_sections. Note where "sections" starts with an underscore
# and where it doesn't. The social settings will make links to
# Twitter, etc., but only if you give the URL.
#
# Also, be sure to customize url and baseurl for your site.
#
# ---------------------------------------------------------------
#
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: SNG
subtitle: Systems Neuroscience Group
description: >- # this means to ignore newlines until "baseurl:"
  Welcome!
author: SNG
email:

# You'll want to customize url and baseurl for your own site:
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sng-newy.github.io" # the base hostname & protocol for your site

# Social settings
# Make sure to include the full url including protocol, e.g. https://github.com/chrisbobbe
twitter_url:
facebook_url:
googleplus_url:
instagram_url:
linkedin_url:
github_url:
stackoverflow_url:
pinterest_url:
slack_url:
dribbble_url:

# Google Analytics Tracking ID goes here:
google_analytics:

# The following settings are NECESSARY for the Prologue theme to run:
remote_theme: chrisbobbe/jekyll-theme-prologue
collections: [home, people, research]

# Add team
team:
    title: "SYSTEMS NEUROSCIENCE GROUP"
    text: "Lorem ipsum dolor sit amet consectetur."
    subtext: Click on our portrait to get more information!
    section: team
    people:
      - name: "Michael Breakspear"
        role: "Group Leader"
        image: assets/images/leonie_borne.jpg
        social:
          - url: https://twitter.com
            icon: fab fa-twitter
          - url: https://linkedin.com
            icon: fab fa-linkedin-in
          - url: https://scholar.google.com.au/citations?user=hrx691cAAAAJ&hl=en
            icon: fab fa-google
  
      - name: "LÃ©onie Borne"
        role: "Postdoc"
        image: assets/images/leonie_borne.jpg
        social:
          - url: https://twitter.com/LeonieBorne
            icon: fab fa-twitter
          - url: https://fr.linkedin.com/in/leonieborne
            icon: fab fa-linkedin-in
          - url: https://www.researchgate.net/profile/Leonie_Borne
            icon: fab fa-researchgate
        research_interest: I am passionate about the use of artificial intelligence in medical imaging. My work aims to develop intelligent algorithms to help the analysis of these images, notably using deep learning. How does our brain work? This is still a mystery today and the algorithms I am developing aim to give us a clearer picture. I have been working in particular on the folds of the cortex, in order to understand their link with the functioning of the brain.

      - name: "Renate Thienel"
        role: "Researcher"
        image: assets/images/leonie_borne.jpg
        newline: true
      - name: "Megan Campbell"
        role: "Postdoc"
        image: assets/images/leonie_borne.jpg
        newline: false
      - name: "Jayson Jeganathan"
        role: "PhD student"
        image: assets/images/leonie_borne.jpg
        social:
          - url: https://twitter.com
            icon: fab fa-twitter
          - url: https://linkedin.com
            icon: fab fa-linkedin-in
        newline: false
      - name: "Nikitas Koussis"
        role: "PhD student"
        image: assets/images/leonie_borne.jpg
        social:
      - name: "Bryan Panton"
        role: "Researcher"
        image: assets/images/leonie_borne.jpg
      - name: "Bob"
        role: "Copain"
        image: assets/images/leonie_borne.jpg
